export const GET_PAYMENTHISTORY_REQUEST= "GET_PAYMENTHISTORY_REQUEST"
export const GET_PAYMENTHISTORY_SUCCESS= "GET_PAYMENTHISTORY_SUCCESS"
export const GET_PAYMENTHISTORY_ERROR= "GET_PAYMENTHISTORY_ERROR"

export const GET_UNIQUEUSER_SUCCESS= "GET_UNIQUEUSER_SUCCESS"
export const GET_UNIQUEUSER_ERROR= "GET_UNIQUEUSER_ERROR"

export const GET_TOTALUNIQUEUSER_SUCCESS= "GET_TOTALUNIQUEUSER_SUCCESS"
export const GET_TOTALUNIQUEUSER_ERROR= "GET_TOTALUNIQUEUSER_ERROR"

export const GET_WEEKLYUNIQUEUSER_SUCCESS= "GET_WEEKLYUNIQUEUSER_SUCCESS"
export const GET_WEEKLYUNIQUEUSER_ERROR= "GET_WEEKLYUNIQUEUSER_ERROR"


export const POST_SENDMESSAGE_REQUEST= "POST_SENDMESSAGE_REQUEST"
export const POST_SENDMESSAGE_SUCCESS= "POST_SENDMESSAGE_SUCCESS"
export const POST_SENDMESSAGE_ERROR= "POST_SENDMESSAGE_ERROR"

export const POST_BULKMESSAGE_REQUEST= "POST_BULKMESSAGE_REQUEST"
export const POST_BULKMESSAGE_SUCCESS= "POST_BULKMESSAGE_SUCCESS"
export const POST_BULKMESSAGE_ERROR= "POST_BULKMESSAGE_ERROR"

export const POST_ANNOUNCEMENT_REQUEST= "POST_ANNOUNCEMENT_REQUEST"
export const POST_ANNOUNCEMENT_SUCCESS= "POST_ANNOUNCEMENT_SUCCESS"
export const POST_ANNOUNCEMENT_ERROR= "POST_ANNOUNCEMENT_ERROR"