export const GET_PAYMENTHISTORY_REQUEST= "GET_PAYMENTHISTORY_REQUEST"
export const GET_PAYMENTHISTORY_SUCCESS= "GET_PAYMENTHISTORY_SUCCESS"
export const GET_PAYMENTHISTORY_ERROR= "GET_PAYMENTHISTORY_ERROR"

export const GET_USERFEEDBACK_REQUEST= "GET_USERFEEDBACK_REQUEST"
export const GET_USERFEEDBACK_SUCCESS= "GET_USERFEEDBACK_SUCCESS"
export const GET_USERFEEDBACK_ERROR= "GET_USERFEEDBACK_ERROR"

export const POST_USERFEEDBACK_SUCCESS= "POST_USERFEEDBACK_SUCCESS"
export const POST_USERFEEDBACK_ERROR= "POST_USERFEEDBACK_ERROR"

export const GET_ADMINSEARCH_REQUEST= "GET_ADMINSEARCH_REQUEST"
export const GET_ADMINSEARCH_SUCCESS= "GET_ADMINSEARCH_SUCCESS"
export const GET_ADMINSEARCH_ERROR= "GET_ADMINSEARCH_ERROR"

export const GET_ADMINDATA_SUCCESS= "GET_ADMINDATA_SUCCESS"
export const GET_ADMINDATA_ERROR= "GET_ADMINDATA_ERROR"

export const GET_SINGLEADMINDATA_SUCCESS= "GET_SINGLEADMINDATA_SUCCESS"
export const GET_SINGLEADMINDATA_ERROR= "GET_SINGLEADMINDATA_ERROR"

export const GET_SUPPORTREQUEST_SUCCESS= "GET_SUPPORTREQUEST_SUCCESS"
export const GET_SUPPORTREQUEST_ERROR= "GET_SUPPORTREQUEST_ERROR"

export const POST_SUPPORTREQUEST_SUCCESS= "POST_SUPPORTREQUEST_SUCCESS"
export const POST_SUPPORTREQUEST_ERROR= "POST_SUPPORTREQUEST_ERROR"

export const POST_ADDADMIN_REQUEST= "POST_ADDADMIN_REQUEST"
export const POST_ADDADMIN_SUCCESS= "POST_ADDADMIN_SUCCESS"
export const POST_ADDADMIN_ERROR= "POST_ADDADMIN_ERROR"

export const GET_UNIQUEUSER_SUCCESS= "GET_UNIQUEUSER_SUCCESS"
export const GET_UNIQUEUSER_ERROR= "GET_UNIQUEUSER_ERROR"

export const GET_TOTALUNIQUEUSER_SUCCESS= "GET_TOTALUNIQUEUSER_SUCCESS"
export const GET_TOTALUNIQUEUSER_ERROR= "GET_TOTALUNIQUEUSER_ERROR"

export const GET_WEEKLYUNIQUEUSER_SUCCESS= "GET_WEEKLYUNIQUEUSER_SUCCESS"
export const GET_WEEKLYUNIQUEUSER_ERROR= "GET_WEEKLYUNIQUEUSER_ERROR"

export const GET_MONTHLYUNIQUEUSER_SUCCESS= "GET_MONTHLYUNIQUEUSER_SUCCESS"
export const GET_MONTHLYUNIQUEUSER_ERROR= "GET_MONTHLYUNIQUEUSER_ERROR"


export const POST_SENDMESSAGE_REQUEST= "POST_SENDMESSAGE_REQUEST"
export const POST_SENDMESSAGE_SUCCESS= "POST_SENDMESSAGE_SUCCESS"
export const POST_SENDMESSAGE_ERROR= "POST_SENDMESSAGE_ERROR"

export const POST_BULKMESSAGE_REQUEST= "POST_BULKMESSAGE_REQUEST"
export const POST_BULKMESSAGE_SUCCESS= "POST_BULKMESSAGE_SUCCESS"
export const POST_BULKMESSAGE_ERROR= "POST_BULKMESSAGE_ERROR"

export const POST_ANNOUNCEMENT_REQUEST= "POST_ANNOUNCEMENT_REQUEST"
export const POST_ANNOUNCEMENT_SUCCESS= "POST_ANNOUNCEMENT_SUCCESS"
export const POST_ANNOUNCEMENT_ERROR= "POST_ANNOUNCEMENT_ERROR"